---
label: default
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: false
  default: default
pages:
- altra storia.md
- _posts/net qui.md
- network qui marche.md
